### ISSUE TITLE
Bot identity overrides

### ISSUE THREAD

**Issue by M1dgard** [UlfS/ghmm#17]
Support bot username and icon overrides. `username` and `icon_url` in the Mattermost payload.

An example payload looks like this:
```json
{
  "username": "robot",
  "icon_url": "http://example.com/somecoolimage.jpg",
  "text": "Hello, this is some text"
}
```

**Comment by UlfS** [comment]
There are currently override values hardcoded for this, which you can see in the [screenshot](https://github.com/UlfS/ghmm/blob/eb5d792275cdd179324ab3f1bee9e6a1753e2544/screenshot.png). This should be good enough for most users.

But this should be easy to implement. I can have a look at this when file-based configuration is implemented, which is part of https://github.com/UlfS/ghmm/issues/16.
